### ISSUE TITLE
Which repository to use?

### ISSUE THREAD

**Issue by baimafeima** [tjfontaine/linode-python#34]
I am confused which repository is the right one when I want to install the linode-python libraries. This one here or https://github.com/linode/python-linode-api which appears to be newer?

**Comment by rtucker** [comment]
Greetings!

This repository is a library for the older, stable Linode API (described at https://www.linode.com/api). This library was mostly developed by third-party developers unaffiliated with Linode, and is generally as feature-complete as it's going to get.

Linode has a newer API (known as version 4) under development, described at https://developers.linode.com/. The linode/python-linode-api repository has Linode's internally-developed implementation for the newer API version.

As for which to use, it's entirely up to you. If you're okay with using an API that is still under active development, Linode's library for API v4 is probably the way I'd go.  Otherwise, the older API is still alive, and tjfontaine/linode-python should work for the foreseeable future.
